### ISSUE TITLE
[Tuleap 718] LLVM: [BUG] the frame index is not removed in the program in the description

### ISSUE THREAD

**Issue by vpalatin** [upmem/llvm-project#12]
@@ From Tuleap issue 718, submitted by jchauzi

@@ Comments:
** When fixed, we can reactivate tasklet_suspend as a simple function (see tasklet.h)

**Comment by ghost** [comment]
``tasklet.h`` does not exist anymore. But it feels like this was already not an issue when we removed ``tasklet.h``, doesn't it? @JordiChauzi

**Comment by JordiChauzi** [comment]
I believe you are correct.
