### ISSUE TITLE
dpu-clang looks for include in host directory

### ISSUE THREAD

**Issue by JordiChauzi** [upmem/llvm-project#30]
By default, `clang` looks at the following include directories for system includes:
- share/upmem/include/stdlib **OK**
- share/upmem/include/syslib **OK**
- lib/clang/9.0.1/include **NOT OK**

Most of the code which would include headers from this directory will not compile for other reasons (like trying to use avx512 on the DPU...), but I think we would rather have a clean include list.

**Comment by ghost** [comment]
The include is added from:
https://github.com/upmem/llvm-project/blob/upmem_release_90/clang/lib/Driver/ToolChains/Clang.cpp#L4238

which is set from:
https://github.com/upmem/llvm-project/blob/upmem_release_90/clang/lib/Driver/Driver.cpp#L151

Set from ``CLANG_RESOURCE_DIR``:
https://github.com/upmem/llvm-project/blob/upmem_release_90/clang/CMakeLists.txt#L221

Just overriding this env variable in our CMake should enable us to "remove" this include path.
Maybe we would want to have our includes not separate like now, and juste have this resource directory pointing onto it instead of what we have in the DPURTE driver?
What do you think @JordiChauzi ?

**Comment by JordiChauzi** [comment]
> The include is added from:
> https://github.com/upmem/llvm-project/blob/upmem_release_90/clang/lib/Driver/ToolChains/Clang.cpp#L4238
> 
> which is set from:
> https://github.com/upmem/llvm-project/blob/upmem_release_90/clang/lib/Driver/Driver.cpp#L151
> 
> Set from `CLANG_RESOURCE_DIR`:
> https://github.com/upmem/llvm-project/blob/upmem_release_90/clang/CMakeLists.txt#L221
> 
> Just overriding this env variable in our CMake should enable us to "remove" this include path.
> Maybe we would want to have our includes not separate like now, and juste have this resource directory pointing onto it instead of what we have in the DPURTE driver?
> What do you think @JordiChauzi ?

Seems good to me.

**Comment by ghost** [comment]
With the modification on installation of dpu-rt to have only 1 include folder?
It will break the compilation process for people that will not have the compiler up-to-date.

**Comment by JordiChauzi** [comment]
That seems reasonable? I do not think we want an user with a compiler and rt lib with different versions.

**Comment by ghost** [comment]
ok, so I'll push the modification in dpu-rt (and llvm) at the end of the day, so that the llvm package will be available tomorrow morning for everyone not recompiling llvm.

**Comment by JordiChauzi** [comment]
@rjodinupmem, actually, we do not want to do this: it may break clang when compiling for the host target.
It needs to be a DPU specific change.

**Comment by ghost** [comment]
You're right... But I'm not a fan of modifying this generic part of clang. Do you have ideas to avoid it?

**Comment by JordiChauzi** [comment]
When looking at the content of the directory, I see a lot of different architecture headers. It seems like this is an OK behavior for clang.
The search order for headers is the right one: first our include directories, then the clang resource directory, so it does not hide our headers.
We may want to reuse some of the provided headers (stddef.h, stdint.h, ...) and remove them from the stdlib directory?

**Comment by ghost** [comment]
ok, but we keep the behavior of allowing dpu program to find header that cannot be compile ?

**Comment by JordiChauzi** [comment]
> ok, but we keep the behavior of allowing dpu program to find header that cannot be compile ?

This seems to be the accepted behavior, yes. The following program finds the include header (and fails later on another system include), even on x86:
```
#include <armintr.h>                                                                                                                                                                                       
                                                                                                                                                                                                        
int main() {                                                                                                                                                                                               
  return 0;                                                                                                                                                                                              
}
```

**Comment by JordiChauzi** [comment]
Not a dpu bug!
