### ISSUE TITLE
Cannot compile x86 programs with lto option without manually install gold plugin

### ISSUE THREAD

**Issue by JordiChauzi** [upmem/llvm-project#31]
```bash
clang main.c -O2 -flto
/usr/bin/ld: /home/jchauzi/work/dpu_tools/build/bin/../lib/LLVMgold.so: error loading plugin: /home/jchauzi/work/dpu_tools/build/bin/../lib/LLVMgold.so: cannot open shared object file: No such file or directory
```
`/usr/bin/ld` does not point to `gold`.
We may need to some option when compiling `llvm` to generate the plugin?

**Comment by JordiChauzi** [comment]
This seems normal for Linux systems.
We may still want to add the plugin in our package for ease of use ?

**Comment by wwolff42** [comment]
fixed in https://github.com/upmem/dpu_tools/pull/217
