### ISSUE TITLE
SW/SD with immediate value syntax is different than SB/SH immediate

### ISSUE THREAD

**Issue by JordiChauzi** [upmem/llvm-project#4]
We can write:
```
sh %zero, 0, 0xACDC
```
But not:
```
sw %zero, 0, 0xACDC
```

The immediate value is a `simm_16` for `sw`/`sd`, but a `suimm_16` for `sh`.

**Comment by JordiChauzi** [comment]
@rjodinupmem Did we fix this when redoing 64-bit extended stores?

**Comment by ghost** [comment]
I don't think so

**Comment by JordiChauzi** [comment]
I am not sure anymore that we want to change the current behavior.
Allowing `sw %zero, 0, 0xACDC` would hide the fact that the stored value is signed-extended.
@rjodinupmem What do you think?
