### ISSUE TITLE
lldb: dpu_list could filter by state RUNNING/FAULT/etc

### ISSUE THREAD

**Issue by aghiti** [upmem/llvm-project#50]

**Comment by ghost** [comment]
@upmem/sw

**Comment by ghost** [comment]
Ideas:
- default output should be a bit more condensed. 1 line per rank? If every DPUs are in the same state: easy. Otherwise print that DPUs are in different state?
- an option to have the full output (DPU per DPU), as it is now.
- Filter full output by state (RUNNING, IDLE, ERROR)

**Comment by ghost** [comment]
The code:
https://github.com/upmem/llvm-project/blob/upmem_release_100/lldb/scripts/dpu/dpu_commands.py#L376
