### ISSUE TITLE
Code crashes on function call with many parameters as input

### ISSUE THREAD

**Issue by jlegriel** [upmem/llvm-project#63]
To reproduce:
~jlegriel/my_tests/compil_stack_11param_issue
>> make
>> dpu-lldb -- test
>> r
>> memory fault

The test case is simple, it has two nested functions with a large number of parameters.
The problem actually happens when using a function with at least 11 parameters as input (which is not recommended though...).

Up to 8 parameters, the values are passed through registers r0 to r7. With more than 8, they are passed on the stack.
The first thing the callee function does is to push the parameter values from registers to its stack.
And for some reason which looks like a bug, r0 is pushed at offset -4 of the stack pointer in r22, which is where the caller stack pointer value was saved (as explained in the DPU ABI doc).
Because the caller stack pointer is erased with value 0, the program later crashes with a memory fault as it tries to access a variable on its stack, with a negative offset to r22 which is supposed to be a positive value.
Using 10 parameters in the function, r0 is however pushed at offset 0 which is OK.

Below is the assembly code where the callee function retrieves parameters from registers and push it to its stack:

80000058 <titi>:
  80000058: ff ff ce 44 5b 74 00 00       lw r8, r22, -20
  80000060: ff ff 0f 44 db 74 00 00       lw r9, r22, -16
  80000068: ff ff 4f 44 5b 75 00 00       lw r10, r22, -12
  **80000070: ff ff c0 45 d8 7f 00 00       sw r22, -4, r0    => r22 - 4 is the caller stack pointer, it is erased**
  80000078: 00 00 02 44 58 7c 00 00       sw r22, 0, r1
  80000080: 00 00 44 44 58 7c 00 00       sw r22, 4, r2
  80000088: 00 00 86 44 58 7c 00 00       sw r22, 8, r3

**Comment by aharries-upmem** [comment]
Fixed with https://github.com/upmem/llvm-project/pull/65
