### ISSUE TITLE
Update to latest LLVM

### ISSUE THREAD

**Issue by JulianvDoorn** [upmem/llvm-project#75]
Currently the compiler is based on LLVM 12, but the latest LLVM is at 17. Support for in-order machine code analysis (mca) was added to LLVM 13. It would actually be nice if I could use this tool for UPMEM DPU machine code, therefore it would be nice if you could merge LLVM 13 or later into this repository. I tried it myself but about 200 files are conflicting and I do not have enough domain knowledge to solve some issues regarding changes to tablegen, but most of the conflicts were quite trivial and even I could solve them.

**Comment by wwolff42** [comment]
Upgrading to newer LLVM version is in progress.
